# Generated by Django 4.2.2 on 2023-08-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffno', models.CharField(max_length=100)),
                ('departselect', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('genderselect', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
